[alembic]
# path to migration scripts
script_location = alembic
sqlalchemy.url = postgresql://postgres:Brian7350@localhost:5432/bcc_nims

[log]
level = INFO
# file_config = %(here)s/alembic_logging.ini
